[package]
name = "russh"
version = "0.5.0"
edition = "2021"
authors = ["Nikhil Prabhu <nikhilprabhu98@gmail.com>"]
license = "GPL-3"
repository = "https://github.com/nikhil-prabhu/russh"
keywords = ["pyo3", "python", "ssh"]

[badges]
maintenance = { status = "experimental" }

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true

[dependencies]
pyo3 = { version = "0.23.3", features = ["extension-module"] }
ssh2 = "0.9.4"
