[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "russh"
version = "0.5.0"
description = "Fast, efficient, and easy-to-use Python SSH client library"
requires-python = ">=3.7"
license = { text = "GPL-3.0-only" }
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Intended Audience :: Developers",
]

[tool.hatch.metadata]
requires-python = ">=3.7"

[tool.hatch.build.targets.wheel]
args = ["--release"]

[tool.hatch.envs.default]
description = "The default development environment"
dependencies = [
    "maturin>=1.0,<2.0",
]

[tool.maturin]
features = ["pyo3/extension-module"]
strip = true
